# 获取商户列表数据
query pageMerchant($input: MerchantPageInput) {
  pageMerchant(input: $input) {
    records {
      id
      name
      userName
      phone
      orgGroupName
      orgGroupId
      orgName
      orgId
    }
    pageCurrent
    pageSize
    totalRecords
  }
}
# 获取商户信息数据
query merchant($input: MerchantIdInput) {
  merchant(input: $input) {
    id
    name
    userName
    userId
    phone
    orgGroupName
    orgGroupId
    orgName
    orgId
  }
}
#表单模糊搜索负责人数据
query searchUser($input: SearchUserInput) {
  searchUser(input: $input) {
    userId
    userName
    phone
    used
  }
}
# 新增商户
mutation creteMerchant($input: MerchantInput) {
  creteMerchant(input: $input)
}
# 修改商户
mutation updateMerchant($input: MerchantInput) {
  updateMerchant(input: $input)
}
