# 商品类型
query peachCommodityTypeOption {
  peachCommodityTypeOption {
    label
    value
  }
}
# 商品品类
query peachCategoryOption {
  peachCategoryOption {
    label
    value
  }
}
# 商品list
query peachPageCommodityManage($pageCommodityInput: PeachPageCommodityInput, $page: Page) {
  peachPageCommodityManage(pageCommodityInput: $pageCommodityInput, page: $page) {
    pageCurrent
    pageSize
    totalRecords
    records {
      commodityId
      commodityName
      commodityTypeId
      commodityTypeName
      categoryId
      categoryName
      varietyId
      varietyName
      originId
      originName
      skuQuantity
      status
    }
  }
}
mutation peachUpdateCommodityStatus($updateCommodityStatusInput: PeachUpdateCommodityStatusInput) {
  peachUpdateCommodityStatus(updateCommodityStatusInput: $updateCommodityStatusInput)
}

query peachPageNoCommodity($pageNoCommodityInput: PeachPageNoCommodityInput, $page: Page) {
  peachPageNoCommodity(pageNoCommodityInput: $pageNoCommodityInput, page: $page) {
    pageCurrent
    pageSize
    totalRecords
    records {
      commodityId
      commodityName
      commodityTypeName
      commodityTypeId
      commodityCategoryName
      commodityVarietyName
      commodityPlaceOriginName
      commodityCategoryId
    }
  }
}
query peachOriginOption($categoryId: Int!) {
  peachOriginOption(categoryId: $categoryId) {
    label
    value
  }
}
query peachVarietyOption($categoryId: Int!) {
  peachVarietyOption(categoryId: $categoryId) {
    label
    value
  }
}
# query pitayaTableHead($commodityId: Int) {
#   pitayaTableHead(commodityId: $commodityId) {
#     spec {
#       specId
#       specName
#     }
#     other {
#       key
#       title
#     }
#   }
# }
query peachNotChosenSkuOption($commodityId: Int!) {
  peachNotChosenSkuOption(commodityId: $commodityId) {
    commoditySkuId
    optionId
  }
}
mutation peachUpdateSkuStatus($updateStatusInput: PeachUpdateStatusInput) {
  peachUpdateSkuStatus(updateStatusInput: $updateStatusInput)
}
mutation peachCreateCommoditySku($commoditySkuId: [Int]) {
  peachCreateCommoditySku(commoditySkuId: $commoditySkuId)
}
mutation peachCreateCommodity($createCommodityInput: PeachListCreateCommodityInput) {
  peachCreateCommodity(createCommodityInput: $createCommodityInput)
}

query peachPageSku($pageSku: PeachPageSkuInput) {
  peachPageSku(pageSku: $pageSku) {
    pageCurrent
    pageSize
    totalRecords
    records {
      commoditySkuId
      skuOption {
        specId
        optionName
      }
      status
    }
  }
}
