#库存管理盘点查看
query pageTakeStockRecord($input: TakeStockRecordInput) {
  pageTakeStockRecord(input: $input) {
    records {
      checkId
      orgName
      checkDate
      totalStatus
      warehouseName
      checkNum
      username
      createTime
      remark
    }
    pageCurrent
    pageSize
    totalRecords
  }
}
#库存管理盘点查看详情页
query getTakeStockRecordDetail($input: TakeStockRecordDetailInput) {
  getTakeStockRecordDetail(input: $input) {
    warehouseName
    checkDate
    abnormalQuantity
    username
    remark
    createTime
    orgName
    orgId
    records {
      checkStatus
      stockOrderCode
      commoditySkuName
      unitQuantity
      checkUnitQuantity
      orderType
      remark
      batchCode
      skuId
    }
  }
}
#仓库下拉
query listWarehouseOption($input: WarehouseOptionInput) {
  listWarehouseOption(input: $input) {
    id
    name
  }
}
#商户下拉
query merchantOption {
  merchantOption {
    label
    value
  }
}
