## 成品 BOM 清单分页列表
query pitayaPageCommodityBom($commodityName: String, $page: Page) {
  pitayaPageCommodityBom(commodityName: $commodityName, page: $page) {
    pageCurrent
    pageSize
    totalRecords
    records {
      commodityBomId
      commoditySkuId
      commodityTypeName
      commodityCategoryName
      commodityName
      commoditySpecOptionName
    }
  }
}

## 获取 sku 列表
query pitayaPageConditionToGetSku($conditionToGetSkuInput: PitayaConditionToGetSkuInput, $page: Page) {
  pitayaPageConditionToGetSku(conditionToGetSkuInput: $conditionToGetSkuInput, page: $page) {
    pageCurrent
    pageSize
    totalRecords
    records {
      commodityId
      commodityName
      commodityTypeId
      commodityTypeName
      commoditySkuId
      commoditySpecOptionName
      unitId
      unitName
      categoryId
      categoryName
      varietyId
      varietyName
      placeOriginId
      placeOriginName
    }
  }
}

## 查询果品 SPU
query pitayaPageCommoditySpuManage($pageCommodityInput: PitayaPageCommodityInput, $page: Page) {
  pitayaPageCommodityManage(pageCommodityInput: $pageCommodityInput, page: $page) {
    pageCurrent
    pageSize
    totalRecords
    records {
      commodityId
      commodityName
      commodityTypeId
      commodityTypeName
      categoryId
      categoryName
      varietyId
      varietyName
      placeOriginId: originId
      placeOriginName: originName
    }
  }
}

## 根据 skuId 查询详情
query pitayaCommoditySkuDetailOnBom($commoditySkuId: Int) {
  pitayaCommoditySkuDetail(commoditySkuId: $commoditySkuId) {
    commoditySkuId
    commodityTypeId
    commodityTypeName
    commodityId
    commodityName
    categoryId
    categoryName
    varietyId
    varietyName
    placeOriginId
    placeOriginName
    commoditySpecName
    commoditySpecOptionName
  }
}

## 根据 bomId 获取配料列表
query pitayaListBurden($bomId: Int) {
  pitayaListBurden(bomId: $bomId) {
    commodityBomDetailId
    commodityTypeId
    commodityTypeName
    commodityCategoryId
    commodityCategoryName
    commodityId
    commodityName
    commoditySkuId
    commoditySpecOptionName
    quantity
    quantityUnit
    quantityUnitName
  }
}

## 删除成品 BOM 清单
mutation pitayaDeleteCommodityBom($bomId: Int) {
  pitayaDeleteCommodityBom(bomId: $bomId)
}

## 新增成品 BOM 清单
mutation pitayaSaveCommodityBom($saveCommodityBomInput: PitayaSaveBomInput) {
  pitayaSaveCommodityBom(saveCommodityBomInput: $saveCommodityBomInput)
}

## 更新成品 BOM 清单
mutation pitayaUpdateCommodityBom($updateCommodityBomInput: PitayaUpdateBomInput) {
  pitayaUpdateCommodityBom(updateCommodityBomInput: $updateCommodityBomInput)
}
