## 品种和产地
query selectVarietyAndPlaceByCategoryId($categoryId: Int) {
  selectVarietyByCategoryId(categoryId: $categoryId) {
    value: varietyId
    label: varietyName
  }

  selectPlaceByCategoryId(categoryId: $categoryId) {
    value: placeId
    label: placeName
  }
}

## 规格类型
query specs($specsInput: SpecsInput) {
  specs(specsInput: $specsInput) {
    specId
    specName
    specOption {
      optionId
      optionName
      specId
    }
  }
}

## 品种组 列表
query pageVarietyGroup($name: String, $page: Page) {
  pageVarietyGroup(name: $name, page: $page) {
    pageCurrent
    pageSize
    totalRecords
    records {
      groupId
      groupName
    }
  }
}

## 品种组 新增
mutation createVarietyGroup($groupName: String!) {
  createVarietyGroup(groupName: $groupName) {
    groupId
    groupName
  }
}

## 品种组 更新
mutation updateVarietyGroup($varietyGroupInput: VarietyGroupInput) {
  updateVarietyGroup(varietyGroupInput: $varietyGroupInput) {
    groupId
    groupName
  }
}

## 品种组 详情
query varietyGroupDetail($id: Int!) {
  varietyGroupDetail(id: $id) {
    groupId
    groupName
  }
}

## 某个品种组关联的数据 列表
query pageVarietyGroupSku($groupId: Int!, $page: Page) {
  pageVarietyGroupSku(groupId: $groupId, page: $page) {
    pageCurrent
    pageSize
    totalRecords
    records {
      varietySkuId
      groupId
      skuId
      categoryName
      spuName
      skuName
    }
  }
}

## 创建某个品种的关联数据
mutation createVarietyGroupSku($createVarietyGroupSkuInput: CreateVarietyGroupSkuInput) {
  createVarietyGroupSku(createVarietyGroupSkuInput: $createVarietyGroupSkuInput)
}

## 某个品种组关联的数据 删除关联
mutation delVarietyGroupSku($delVarietyGroupSkuInput: DelVarietyGroupSkuInput) {
  delVarietyGroupSku(delVarietyGroupSkuInput: $delVarietyGroupSkuInput)
}

## 某些条件下的 SKU
query pageGroupSku($groupSkuInput: GroupSkuInput, $page: Page) {
  pageGroupSku(groupSkuInput: $groupSkuInput, page: $page) {
    records {
      commoditySkuId
      skuCommoditySpecOptionList {
        specId
        optionName
      }
    }
    pageCurrent
    pageSize
    totalRecords
  }
}
